#!/usr/bin/env bash
#Nginx
sudo apt-get update
sudo apt-get -y install nginx
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'
sudo bash -c 'echo "server {
	listen 80;
	listen [::]:80 default_server;
	root   /etc/nginx/html;
	index  index.html;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4
	}
}" > /etc/nginx/sites-available/default'
sudo service nginx restart
