#!/usr/bin/env bash
# conf
# nginx in web-01
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

# name debugging
hostt=$(hostname)
hed="\\\n\tadd_header X-Served-By $hostt;\n"
chk=$(grep "X-Server-by" /etc/nginx/sites-available/default)
if [[ -z $chk ]]; then
    sudo sed -i "23i $hed" /etc/nginx/sites-available/default
fi

# html file 
echo "Hello World!" > /var/www/html/index.html

# configuration redirection
chk=$(grep "redirect_me" /etc/nginx/sites-available/default)
str="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
if [[ -z $chk ]]; then
    sudo sed -i "42i $str" /etc/nginx/sites-available/default
fi

# the err page 404
chk=$(grep "error_page 404" /etc/nginx/sites-available/default)
err="\\\n\terror_page 404 /custom_404.html;\n"
if [[ -z $chk ]]; then
    echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
    sudo sed -i "40i $err" /etc/nginx/sites-available/default
fi

# restart nginx
sudo service nginx restart
