#!/usr/bin/env bash
#"bad luck from China" 4th
#"bad luck from Japan"  9th
#"bad luck from Italy" 17th

x=1

while [ $x -le 20 ]
do
  echo "$x"
  case $x in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( x++ ))
done
