#!/usr/bin/env bash
# fixes web server
chmod 644 /etc/nginx/nginx.conf
sed -i 's/^\s*#\s*user.*$/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
pkill apache2
sudo -u nginx service nginx start
